### ISSUE TITLE
Thanks!!

### ISSUE THREAD

**Issue by cicorias** [mayer79/lightgbm_r_binaries#2]
This is a great help.

I just wanted to thank you and I'll push a readme change to the lightgbm folks if they accept it to reference this.  

The lightgbm docs on Windows build and install are in sloppy state and this added 10 years back to my life. 🥇

**Comment by mayer79** [comment]
Ha, easy gained life :-) 

No need to reference this on the lgb repo though. Nevertheless I will add the latest release for R 3.6 and R 4.0 shortly.

**Comment by mayer79** [comment]
Just a note: I added the newest LightGBM version for R 3.6.3.
